# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus3', '0002_parking_dateexpiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='adminRight',
            field=models.BooleanField(default=False),
        ),
    ]
