# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus3', '0003_person_adminright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcardtype',
            name='CardAmt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
